export type Page = 'Dashboard'|'Boost'|'Startup'|'Cleaner'|'Processes'|'Gaming Mode'|'Performance'|'History'|'Settings'
export interface User { id:string; name:string; email?:string; licenseType:'free'|'pro'; createdAt:string }
export interface Device { id:string; name:string; osName:string; osBuild:string; architecture:'32bit'|'64bit'; cpuModel:string; cpuCores:number; ramTotalMb:number; gpuModel:string; storageType:'HDD'|'SSD'|'NVMe'|'Unknown'; storageTotalGb:number }
export interface PerformanceScan { id:string; deviceId:string; cpuUsagePercent:number; ramUsagePercent:number; diskUsagePercent:number; freeStorageGb:number; startupAppCount:number; backgroundProcessCount:number; performanceScore:number; createdAt:string }
export interface Issue { id:string; category:'startup'|'ram'|'cpu'|'disk'|'storage'|'visual'|'background'; title:string; description:string; severity:'low'|'medium'|'high'; estimatedImpact:'low'|'medium'|'high'; recommendedAction:string; canAutoFix:boolean }
export interface StartupApp { id:string; name:string; publisher:string; path:string; impactLevel:'low'|'medium'|'high'|'unknown'; isEnabled:boolean; isCritical:boolean }
export interface OptimizationAction { id:string; category:'startup'|'cleanup'|'process'|'visual'|'power'|'gaming'; actionName:string; description:string; previousState:Record<string,unknown>; newState:Record<string,unknown>; isReversible:boolean; status:'applied'|'failed'|'reverted'; createdAt:string }
export interface Metric {cpu:number|null;ram:number|null;disk:number|null;gpu:number|null;diskCapacityPercent:number|null;diskFreeGb:number|null;diskTotalGb:number|null;totalMemoryGb:number;availableMemoryGb:number;cpuModel:string;sampledAt:string;activitySampledAt:string;}
export interface SystemInfo {hostname:string;osName:string;osVersion:string;architecture:string;cpuModel:string;cpuCores:number;gpuModel:string|null;gpuName:string|null;battery:{available:boolean;percent:number|null;charging:boolean|null;timeRemainingMinutes:number|null;healthPercent:number|null}}
